### ISSUE TITLE
Lambda fails with Cannot find module /var/task/redshiftmonitor

### ISSUE THREAD

**Issue by aharonen** [tableau/redshift-monitor#1]
Any idea someone?
{
  "errorMessage": "Cannot find module '/var/task/redshiftmonitor'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

**Comment by russch** [comment]
Perhaps this?

https://stackoverflow.com/questions/31664313/aws-lambda-function-is-returning-cannot-find-module-index-yet-the-handler-in

**Comment by aharonen** [comment]
Thanks for the help, 

I managed to fix this by renaming the function exports.myHandler to myHandler and by creating a new zip where the file redshiftmonitor is on the root folder of this zip and not under a folder.
